language: node_js

services: 
  - docker

script: 
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy 
  - docker tag udagram-api-feed duypk2000/udagram-api-feed:v1
  - docker tag udagram-api-user duypk2000/udagram-api-user:v1
  - docker tag udagram-frontend duypk2000/udagram-frontend:v2
  - docker tag reverseproxy duypk2000/reverseproxy:v1
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push duypk2000/udagram-api-feed:v1
  - docker push duypk2000/udagram-api-user:v1
  - docker push duypk2000/udagram-frontend:v2
  - docker push duypk2000/reverseproxy:v1

