apiVersion: apps/v1
kind: Deployment 
metadata:
  name: backend-feed-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed-container 
          image: duypk2000/udagram-api-feed:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: udagram-configmap