apiVersion: apps/v1
kind: Deployment 
metadata:
  name: backend-feed-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed-container 
          image: duypk2000/udagram-api-feed:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          envFrom:
            - configMapRef:
                name: udagram-configmap
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USERNAME
              valueFrom: 
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USERNAME
          volumeMounts:
            - mountPath: "/root/.aws"
              name: "aws-secret"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret